language: perl

perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

install:
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla Software::License::GPL_2::or_later
  - dzil authordeps --missing | cpanm --quiet --notest
  - dzil listdeps --missing | cpanm --quiet --notest

script:
  - dzil smoke

# run code coverage & generate POD (only once)
after_success:
  - test $TRAVIS_PERL_VERSION = '5.22' && cpanm --quiet --notest --skip-satisfied Dist::Zilla::App::Command::cover Devel::Cover::Report::Codecov && dzil cover -test -report codecov
  - test $TRAVIS_PERL_VERSION = '5.22' && make

# export POD to gh-pages (only once)
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: /tmp/pod
  on:
    branch: travis-pod
    perl: '5.22'
